### ISSUE TITLE
Do it use VS2013 vector calling convention?

### ISSUE THREAD

**Issue by KindDragon** [Cincinesh/tue#17]
Do it use SIMD `_vectorcall`?
http://blogs.msdn.com/b/vcblog/archive/2013/07/12/introducing-vector-calling-convention.aspx

**Comment by Cincinesh** [comment]
Sorry, it doesn't. It's a header-only library and in my (admittedly limited) testing, most of the functions ended up being inlined, so the calling convention doesn't matter in most cases. Passing simd types accelerated by SSE/SSE2 intrinsics (such as float32x4, int64x2, etc) by value in your own _vectorcall functions, however, should work since they meet the Homogeneous Vector Aggregate data-type (HVA) requirements.

**Comment by KindDragon** [comment]
Thank you for answering
